### ISSUE TITLE
Readme doesn't match 1.0 release

### ISSUE THREAD

**Issue by edvaldeysteinsson** [StephaneBg/SimpleNumberPicker#1]
FYI, your readme doesn't match the 1.0 release. In order to get what you describe in the readme the developer would need to use
compile 'com.github.StephaneBg:SimpleNumberPicker:master-SNAPSHOT'
i suggest making a new release that matches the readme to avoid confusion.

**Comment by StephaneBg** [comment]
Hello, I tried it and it works fine. BTW, I added a badge in the readme.

**Comment by edvaldeysteinsson** [comment]
I tried it again and i still get this issue, you can download the aar from here
[https://jitpack.io/com/github/StephaneBg/SimpleNumberPicker/1.0/SimpleNumberPicker-1.0.aar](https://jitpack.io/com/github/StephaneBg/SimpleNumberPicker/1.0/SimpleNumberPicker-1.0.aar)
rename it to .zip und unpack it then take the classes.jar and upload it to
http://www.javadecompilers.com/
and then take a look at
com.sbgapps.simplenumberpicker.hex.HexaPickerDialog
the builder in that one looks like this when i check it

    public static class Builder {
      public Builder() {}
      
      private String mKey = "HexPickerDialog";
      private int mMinLength = -1;
      private int mMaxLength = -1;
      
      public Builder setKey(String index) {
        mKey = index;
        return this;
      }
      
      public Builder setMinLength(int minLength) {
        mMinLength = minLength;
        return this;
      }
      
      public Builder setMaxLength(int maxLength) {
        mMaxLength = maxLength;
        return this;
      }
      
      public HexaPickerDialog create() {
        return HexaPickerDialog.newInstance(mKey, mMinLength, mMaxLength);
      }
    }


but the one you have here looks like this

    public static class Builder {

        private int reference = DEFAULT_REFERENCE;
        private int minLength = NO_MIN_LENGTH;
        private int maxLength = NO_MAX_LENGTH;
        private int theme = R.style.SimpleNumberPickerTheme;

        public Builder setReference(int reference) {
            this.reference = reference;
            return this;
        }

        public Builder setMinLength(int minLength) {
            this.minLength = minLength;
            return this;
        }

        public Builder setMaxLength(int maxLength) {
            this.maxLength = maxLength;
            return this;
        }

        public Builder setTheme(int theme) {
            this.theme = theme;
            return this;
        }

        public HexaPickerDialog create() {
            return newInstance(reference, minLength, maxLength, theme);
        }
    }


Not sure what's going on, i might be doing something wrong but i've tried to exclude user error on my side =), i thought you might want to know given that you've taken the time to open source something.

**Comment by StephaneBg** [comment]
Hello,
everything should be fine with release 1.1.

Thanks for the feedback.
