### ISSUE TITLE
Doesnt show keyboard items

### ISSUE THREAD

**Issue by komok2013** [StephaneBg/SimpleNumberPicker#10]
![screenshot_1510836069](https://user-images.githubusercontent.com/4245585/32893105-6864c584-cae9-11e7-878f-ecafb7e08bed.png)

ver 1.4

**Comment by StephaneBg** [comment]
Hello, thanks for pointing this out.
Can you try with the latest snapshot please ?

`implementation 'com.github.StephaneBg:SimpleNumberPicker:master-SNAPSHOT'`

**Comment by StephaneBg** [comment]
Should be fixed with release 1.5.
