### ISSUE TITLE
Does not delete last once digit.

### ISSUE THREAD

**Issue by ForesThule** [StephaneBg/SimpleNumberPicker#11]
Android Phone running lollipop 5.1.1. 
![device-2017-11-24-143503](https://user-images.githubusercontent.com/10618918/33208992-f3a5ff50-d124-11e7-89d2-94fdd66649df.gif)

**Comment by StephaneBg** [comment]
I wasn't able to reproduce. Which version of the library do you use?

**Comment by ForesThule** [comment]
'com.github.StephaneBg:SimpleNumberPicker:1.5'
sory android  version is 5.0

**Comment by ForesThule** [comment]
phone - Samsung Galaxy Note 3

**Comment by ForesThule** [comment]
sory - version is 5.0

**Comment by StephaneBg** [comment]
I tried on emulator on API 21 and I wasn't able to reproduce.
Close it for the moment.
