### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by deibeeed** [StephaneBg/SimpleNumberPicker#2]
It seems that there are some problems when using this dependency.

`compile 'com.github.StephaneBg:SimpleNumberPicker:1.0'`

the code above cannot find the `Builder.setReference()` and other Builder codes. It only shows `Builder.setKey()`

This works
`compile 'com.github.StephaneBg:SimpleNumberPicker:master-SNAPSHOT'`

**Comment by StephaneBg** [comment]
Hello,
can you try 1.1 release please?

**Comment by StephaneBg** [comment]
Looks like there is no more issue with release 1.1.
Thanks for the feedback.

**Comment by deibeeed** [comment]
i'm so sorry i was not able to make release 1.1.

I planned to do it yesterday but I completely forgot.

Again, thanks for making this library and for making the release 1.1.

I'll see what i can do to make this library better :)

Cheers,
david.andrew
