### ISSUE TITLE
i can see only first 6 digit while typing 

### ISSUE THREAD

**Issue by ghost** [StephaneBg/SimpleNumberPicker#5]
i can see only first 6 digit while typing.

Can you give alternative solution  for this.

**Comment by StephaneBg** [comment]
Hello,
could you describe the issue with more details please?
Which picker? How to reproduce?

**Comment by ghost** [comment]
Find the attached image below:

<img width="631" alt="issue" src="https://cloud.githubusercontent.com/assets/22938251/24395908/f2a9939c-13be-11e7-9d0d-72a1a133c315.png">

**Comment by StephaneBg** [comment]
I will use an autofit TextView to show all digits.

**Comment by ghost** [comment]
i think can set Multi line property.

**Comment by StephaneBg** [comment]
I don't want to because it'll look ugly.

**Comment by StephaneBg** [comment]
Text will autofit since last commit.
